exception unexpected EOF while parsing (<string>, line 0) from the adapter of i:clickEqualsCleared
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 442, in adapter of action "i:clickEqualsCleared"
    number = result = eval(expression)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

exception validateExpression() did not recognize expression 88 from the adapter of i:keyEqualsOperation
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 521, in adapter of action "i:keyEqualsOperation"
    validateExpression(expression)
  File "/tmp/remote_pyaal.hP6Qii.py", line 56, in validateExpression
    raise AssertionError('validateExpression() did not recognize expression ' + _expression)
AssertionError: validateExpression() did not recognize expression 88

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

exception validateExpression() did not recognize expression 15 from the adapter of i:clickEqualsNumber
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 698, in adapter of action "i:clickEqualsNumber"
    validateExpression(expression)
  File "/tmp/remote_pyaal.hP6Qii.py", line 56, in validateExpression
    raise AssertionError('validateExpression() did not recognize expression ' + _expression)
AssertionError: validateExpression() did not recognize expression 15

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

exception validateExpression() did not recognize expression ++25 from the adapter of i:keyEqualsOperation
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 521, in adapter of action "i:keyEqualsOperation"
    validateExpression(expression)
  File "/tmp/remote_pyaal.hP6Qii.py", line 56, in validateExpression
    raise AssertionError('validateExpression() did not recognize expression ' + _expression)
AssertionError: validateExpression() did not recognize expression ++25

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

exception invalid syntax (<string>, line 1) from the adapter of i:keyEqualsNumber
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 645, in adapter of action "i:keyEqualsNumber"
    number = result = eval(expression)
  File "<string>", line 1
    53*94+*44-49
          ^
SyntaxError: invalid syntax

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

exception invalid syntax (<string>, line 1) from the adapter of i:keyEqualsResult
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 770, in adapter of action "i:keyEqualsResult"
    number = result = eval(expression)
  File "<string>", line 1
    53*94+*44-49
          ^
SyntaxError: invalid syntax

exception invalid syntax (<string>, line 1) from the adapter of i:keyEqualsNumber
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 645, in adapter of action "i:keyEqualsNumber"
    number = result = eval(expression)
  File "<string>", line 1
    53*94+*44-4*56-/30//98-36
          ^
SyntaxError: invalid syntax

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

exception invalid syntax (<string>, line 1) from the adapter of i:keyEqualsNumber
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 645, in adapter of action "i:keyEqualsNumber"
    number = result = eval(expression)
  File "<string>", line 1
    53*94+*44-4*56-/30//98-36*64/0
          ^
SyntaxError: invalid syntax

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

exception validateExpression() did not recognize expression 38++43 from the adapter of i:keyEqualsNumber
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 649, in adapter of action "i:keyEqualsNumber"
    validateExpression(expression)
  File "/tmp/remote_pyaal.hP6Qii.py", line 56, in validateExpression
    raise AssertionError('validateExpression() did not recognize expression ' + _expression)
AssertionError: validateExpression() did not recognize expression 38++43

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

exception validateExpression() did not recognize expression 39++7 from the adapter of i:clickEqualsNumber
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 168, in adapter_execute
    rv = self.call(self._all_adapters[i-1], adapter_call_arguments)
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 698, in adapter of action "i:clickEqualsNumber"
    validateExpression(expression)
  File "/tmp/remote_pyaal.hP6Qii.py", line 56, in validateExpression
    raise AssertionError('validateExpression() did not recognize expression ' + _expression)
AssertionError: validateExpression() did not recognize expression 39++7

exception 'int' object has no attribute 'find' from the adapter of Result
Traceback (most recent call last):
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 188, in tag_execute
    rv = self.call(self._all_tagadapters[i-1])
  File "/share/ohjcourses/testaus/installations/fmbt-0.29-0/lib64/python2.7/site-packages/aalmodel.py", line 99, in call
    rv = eval(func.func_code, self._variables)
  File "g.py.aal", line 712, in adapter of tag "Result"
    validateExpression(result)
  File "/tmp/remote_pyaal.hP6Qii.py", line 46, in validateExpression
    if _expression.find('/') > -1:
AttributeError: 'int' object has no attribute 'find'

